# Numpy

In [2]:
import numpy as np

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [7]:
arr = np.random.uniform(low=0,high=20,size=(4,7))
arr2 = np.random.uniform(low=0,high=20,size=(4,7))
arr

array([[11.76805369,  2.23300559, 11.40112127,  9.34647349, 18.51851586,
        16.54028172,  2.93831692],
       [19.76364475,  1.97982661, 12.60529355,  0.94527122, 16.3445568 ,
        19.68312108,  9.71379354],
       [14.99602153,  4.18105205, 11.91082811,  9.73413429,  2.81547851,
         8.82288593, 16.21480738],
       [18.4933617 ,  1.61898624, 14.31405603, 19.93486779, 19.78637337,
        14.21055371, 12.51436724]])

In [8]:
arr + 100

array([[111.76805369, 102.23300559, 111.40112127, 109.34647349,
        118.51851586, 116.54028172, 102.93831692],
       [119.76364475, 101.97982661, 112.60529355, 100.94527122,
        116.3445568 , 119.68312108, 109.71379354],
       [114.99602153, 104.18105205, 111.91082811, 109.73413429,
        102.81547851, 108.82288593, 116.21480738],
       [118.4933617 , 101.61898624, 114.31405603, 119.93486779,
        119.78637337, 114.21055371, 112.51436724]])

In [9]:
arr + arr2

array([[23.06267258,  7.73701635, 21.78811339, 11.07295289, 24.97017844,
        31.67851252,  3.87608122],
       [27.11847267, 14.48465544, 23.62195154,  1.23092987, 20.90090692,
        20.55878031, 20.22614167],
       [22.27316889, 10.97419391, 27.49791487, 26.05432988, 10.28199169,
        15.47072774, 33.00710301],
       [22.15413745, 15.12659851, 21.38307498, 29.07420181, 35.89108994,
        27.85825084, 13.90882999]])

In [12]:
(arr - arr.min()) / (arr.max()-arr.min())

array([[0.5699322 , 0.06781262, 0.55060938, 0.44241078, 0.92541432,
        0.8212397 , 0.10495461],
       [0.99098332, 0.05448011, 0.61402159, 0.        , 0.81093274,
        0.98674291, 0.46175401],
       [0.73991832, 0.17039756, 0.57745076, 0.46282516, 0.09848589,
        0.41483844, 0.80410008],
       [0.92408969, 0.03547811, 0.70400573, 1.        , 0.99218022,
        0.69855526, 0.60923338]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [22]:
arr = np.random.randint(low = 0, high = 10, size = (8,10))
arr

array([[3, 6, 3, 9, 3, 3, 6, 8, 0, 1],
       [5, 8, 9, 3, 4, 5, 7, 0, 5, 4],
       [6, 6, 2, 4, 4, 0, 2, 1, 8, 0],
       [4, 4, 4, 4, 8, 3, 5, 4, 3, 9],
       [8, 5, 5, 1, 4, 3, 7, 6, 2, 9],
       [6, 1, 3, 1, 8, 6, 5, 4, 0, 3],
       [9, 7, 8, 3, 4, 2, 1, 3, 6, 5],
       [0, 7, 3, 7, 8, 6, 8, 1, 0, 9]])

In [23]:
arr[4, 2]

5

In [24]:
arr[:4,2:5]

array([[3, 9, 3],
       [9, 3, 4],
       [2, 4, 4],
       [4, 4, 8]])

In [28]:
sum_by_row = arr.sum(axis = 1)
sum_by_row

array([42, 50, 33, 48, 50, 37, 48, 49])

In [30]:
min_idx = sum_by_row.argmin()
min_idx, arr[min_idx]

(2, array([6, 6, 2, 4, 4, 0, 2, 1, 8, 0]))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [34]:
x = np.array([1,2,3])
y = np.array([1,4,3])

In [35]:
#(x-y)**2
np.sqrt(np.power(x-y,2).sum())

2.0

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [37]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

In [38]:
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

In [40]:
1*10**(0)
5.32907052*10**(-16)

5.32907052e-16

In [48]:
A @ X @ B

array([[ -7., -21.],
       [-11.,  -8.],
       [ -8.,  -4.]])

In [47]:
-C

array([[ -7, -21],
       [-11,  -8],
       [ -8,  -4]])

## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
import numpy as np
minute = np.loadtxt('minutes_n_ingredients.csv',delimiter = ',', dtype='int32', skiprows=1)
minute[0:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [5]:
mean = np.mean(minute, axis = 0)
mean[1:]


array([2.16010017e+04, 9.05528000e+00])

In [5]:
mx = np.amax(minute, axis=0)
mx[1:]


array([2147483647,         39])

In [6]:
mn = np.amin(minute, axis = 0)
mn[1:]

array([0, 1])

In [4]:
med = np.median(minute, axis = 0)
med[1:]

array([40.,  9.])

3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [44]:
r = minute[np.random.randint(len(minute)+1, size = 10)]
r

array([[156249,     35,     11],
       [133709,     20,     12],
       [303119,     20,      7],
       [179734,     20,     10],
       [434427,    255,     12],
       [277484,     60,     10],
       [ 89326,     40,     10],
       [495324,    285,     15],
       [121955,     40,     10],
       [161387,     75,     11]])

4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [5]:
ch = minute[:,2]
minute[ch<=5]
#rch = np.random.choice(ch, size = 5)
#rch

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [6]:
c = minute[:,2]
c1 = c[c<np.mean(c)].size
p = c1/c.size*100
p

58.802

6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [7]:
mq = minute[:, 1]
q = np.quantile(mq, 0.75, axis = 0)
np.minimum(mq, q)

65.0

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [12]:
m =  minute[:,1]
z = (minute[m == 0]).size
print(z)
z1 = minute[:, 1]
z2 = np.maximum(z1, 1)
z2

1437


array([ 60,  25,  10, ...,  65,   5, 140])

8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [117]:
u = minute[:,2]
uniq, c = np.unique(u, return_counts=True)
res = np.column_stack((uniq, c)) 
print('Ответ 1:\n',res)
a = np.arange(42)
a1 = np.delete(a,0)
np.isin(uniq, a1)
print('////////')
print('Ответ 2:\n',a1[39:])

Ответ 1:
 [[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]
////////
Ответ 2:
 [40 41]


9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [127]:
c = minute[:,2]/z2 # z2 из 7 задания
np.amax(c)

24.0

10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [169]:
s = minute[:,1:]
s1 = s[s[:, 0].argsort()[::-1]]
#s1[:100]
m = np.mean(s1[:100,1])
m    

6.61

11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [50]:
one = 1
zero = 0
stolb = np.where((minute[:,1]<=20) & (minute[:,2]<=5),one,zero).reshape(len(minute[:,1]), 1)
minute1 = np.append(minute,stolb,axis=1)
print(minute1)
el = np.count_nonzero(minute1[:,3], axis=None)
el1 = el/len(minute[:])*100
el1

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


9.552

12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [5]:
rules = [minute[:,1] < 10, (minute[:,1] >= 10) & (minute[:,1] < 20), minute[:,1] >= 20]
cr = ['low', 'medium','high']
S = np.select(rules, cr)
S[0:10]

#не совсем понял задание с трёхмерным массивом и смысл фразы 'характеристики рецепта'(имеется ввиду минуты и ингредиенты 
#                                                                                     требуемые для приготовления?)

array(['high', 'high', 'medium', 'low', 'high', 'high', 'medium',
       'medium', 'low', 'high'], dtype='<U11')

13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [15]:
a = ([5,10])
b = minute[:10,1]
c = minute[:10,2]
b1 = np.dot(b,a[0])
c1 =np.dot(c,a[1])
x = np.stack((b1,c1))
print(x)
np.sum(x/2,axis=0)

[[300 125  50  25 300 200  90  75  35 100]
 [160  70  60  60 140  70  90  50  90  70]]


array([230. ,  97.5,  55. ,  42.5, 220. , 135. ,  90. ,  62.5,  62.5,
        85. ])